config/routes.rb
Rails.application.routes.draw do
  get     "login"    => "sessions#new"
  post    "login"    => "sessions#create"
  delete  "logout"   => "sessions#destroy"

  # get 'welcome/index'

  resources :articles do
    resources :comments
  end

  # get     "login"    => "welcome#index"
    root 'welcome#index'
    resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
    validates :title, presence: true,
                length: { minimum: 5}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  before_action :require_login

  def require_login
    unless logged_in?
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
    @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])

        if @article.update(article_params)
          redirect_to @article
        else
          render 'edit'
        end
    end

    def new
      @article = Article.new
    end

    def create
      @article = Article.new(article_params)

      if @article.save
        redirect_to @article
      else
            render  'new'
      end
    end

    private
      def article_params
        params.require(:article).permit(:title, :text)
      end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article)
    end

    private
        def comment_params
            params.require(:comment).permit(:commenter, :body)
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by name: params[:session][:name].downcase
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "Login success"
      log_in user
      redirect_to user
    else
      flash[:danger] = "Invalid email/password combination"
      render :new
    end
  end

  def destroy
    log_out
    flash[:success] = "You are logged out"
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = "Register Success"
      redirect_to users_path
    else
      flash[:success] = "Register Failed"
      render :new
    end
  end

  def show
    @user = User.find_by id:params[:id]
  end

  private
  def user_params
    params.require(:user).permit :name, :password, :password_confirmation
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def log_out
    session.delete :user_id
  end

  def current_user
    @current_user ||= User.find_by id: session[:user_id]
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h1> Edit article </h1>
<%= form_with(model: @article) do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h2>Listing articles</h2>
<button type="button" class="btn btn-default">
  <%= link_to 'New article', new_article_path %>
</button>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  </thead>
  <tbody>

  <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><button type="button" class="btn btn-info"><%= link_to 'Show', article_path(article) %></button></td>
        <td><button type="button" class="btn btn-warning"><%= link_to 'Edit', edit_article_path(article) %></button></td>
        <td>
          <button type="button" class="btn btn-danger">
            <%= link_to 'Delete', article_path(article),
                        method: :delete,
                        data: {confirm: 'Are you sure ?'}
            %>
          </button>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<%= form_with scope: :article, url: articles_path, local: true do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ]) do |form| %>
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'true' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'true' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <a class="navbar-brand" href="/">Dashboard</a>
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <%= link_to 'Articles Item', controller: 'articles' %>
            </li>
            <li class="nav-item">
            </li>
          </ul>
        </nav>

        <main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
          <div class="table-responsive">
            <section class="content">
              <% flash.each do |key, value| %>
                  <div class="row">
                    <div class="alert alert-<%= key %>">
                      <%= value %>
                    </div>
                  </div>
              <% end %>
            </section>
            <%= yield %>
          </div>
        </main>
      </div>
    </div>
  </body>
</html>

app/views/users/_user.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <div class="text-left col-lg-6", style="padding-left: 0px ">
        <label>User name: <%= @user.name %></label>
      </div>
      <div class="text-right col-lg-6">
        <%= link_to "Logout", logout_path, method: :delete %>
      </div>
    </div>
    <div class="col-lg-offset-3 col-lg-6">
      <%= link_to "List Users", users_path %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h1 class="title">LOGIN APP</h1>
    </div>
    <div class="col-lg-12 form-group">
      <label for="">Welcome</label>
      <%= link_to current_user.name, user_path(current_user) %>
    </div>
    <div class="col-lg-12 form-group">
      <label for="">List Users</label>
      <table class="table">
        <thead>
        <th>ID</th>
        <th>User Name</th>
        </thead>
        <tbody>
        <%= render @user %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-lg-offset-2">
    <%= form_for @user, html: {class: "form-horizontal"} do |f| %>
        <div class="form-group">
          <%= f.label :name, "Name", class: "col-md-2 control-label" %>
          <div class="col-md-6">
            <%= f.text_field :name, class: "form-control", placeholder: "Enter user name" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :password, "Password", class: "col-md-2 control-label" %>
          <div class="col-md-6">
            <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, "Password Confirmation", class: "col-md-2 control-label" %>
          <div class="col-md-6">
            <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Enter password confirmation" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-lg-offset-4">
            <%= f.submit "Register", class: "btn btn-success" %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <div class="text-left col-lg-6", style="padding-left: 0px ">
        <label>User name: <%= @user.name %></label>
      </div>
      <div class="text-right col-lg-6">
        <%= link_to "Logout", logout_path, method: :delete %>
      </div>
    </div>
    <div class="col-lg-offset-3 col-lg-6">
      <%= link_to "List Users", users_path %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<!--<%= link_to 'My Blog', controller: 'articles' %>-->